apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: ClusterIP
  #type: NodePort
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: tornjak-backend-http
      port: 10000
      targetPort: 10000
      protocol: TCP
    - name: tornjak-backend-tls
      port: 20000
      targetPort: 20000
      protocol: TCP
    - name: tornjak-backend-mtls
      port: 30000
      targetPort: 30000
      protocol: TCP
    - name: tornjak-frontend
      port: 3000
      targetPort: 3000
  selector:
    app: spire-server
